version: "3"
services:
  backend:
    build: ./docker
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
